## Travis CI Configuration file

# Use barebones Travis image
language: c

# Only grab latest git commit (no need for history)
git:
  depth: 1

# Cache the compilers folder so we don't have to download and unpack it for every build
cache:
  directories:
    - $HOME/compilers/

# Download and unpack the latest GNU ARM Embedded Toolchain if it's not already there
#  Also add the gcc/bin folder to $PATH
install:
  - export GCC_DIR=$HOME/compilers/gcc-arm-none-eabi-6-2017-q2-update
  - export GCC_ARCHIVE=$HOME/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2
  - export GCC_URL=https://developer.arm.com/-/media/Files/downloads/gnu-rm/6-2017q2/gcc-arm-none-eabi-6-2017-q2-update-linux.tar.bz2?product=GNU%20ARM%20Embedded%20Toolchain,64-bit,,Linux,6-2017-q2-update
  - if [ ! -e $GCC_DIR/bin/arm-none-eabi-gcc ]; then wget -nv $GCC_URL -O $GCC_ARCHIVE; tar xfj $GCC_ARCHIVE -C $HOME/compilers; fi
  - export PATH=$PATH:$GCC_DIR/bin

# List of tests to run ( `./build -w $BOARD $MAIN` )
env:
  - BOARD=uos3-proto MAIN=blinky
  - BOARD=uos3-proto MAIN=serial-test
  - BOARD=uos3-proto MAIN=tx-test
  - BOARD=uos3-proto MAIN=txrx-uart

# Command to run tests
script: ./build -w $BOARD $MAIN

# Additional jobs for Tests, and Doxygen documentation (only on master branch)
jobs:
  include:
    - stage: Module Tests
      env: 
      script: ./test -w
    - stage: Doxygen
      if: branch = phil-work
      cache: skip
      install: skip
      addons:
        apt:
          packages:
            - doxygen
      env: 
      script: tools/travis_doxygen_docs.sh
